### PR TITLE
LPS-191773

### PR DESCRIPTION
**Pull request by CaiocSiqueira**

### CODE REVIEW

**Comment by CaiocSiqueira** [comment]
ci:test:search-es8-remote-minimum

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:search-es8-remote-minimum:nocompile

**Comment by CaiocSiqueira** [comment]
ci:test:sf

**Comment by CaiocSiqueira** [comment]
ci:test:search-es8-remote-minimum

**Comment by CaiocSiqueira** [comment]
ci:test:search-es8-remote

**Comment by CaiocSiqueira** [comment]
ci:test:commerce-es8-remote

**Comment by CaiocSiqueira** [comment]
ci:test:workflow-es8-remote

**Comment by CaiocSiqueira** [comment]
ci:test:commerce-es8-remote

**Comment by CaiocSiqueira** [comment]
ci:test:search-es8-remote-minimum

**Comment by CaiocSiqueira** [comment]
ci:test:workflow-es8-remote

**Comment by CaiocSiqueira** [comment]
ci:test:search-es8-remote

**Comment by CaiocSiqueira** [comment]
ci:test:commerce-es8-remote

**Comment by CaiocSiqueira** [comment]
ci:test:search-es8-remote-minimum

**Comment by CaiocSiqueira** [comment]
ci:test:workflow-es8-remote

**Comment by CaiocSiqueira** [comment]
ci:test:search-es8-remote

**Comment by joshchong** [comment]
continued in https://github.com/joshchong/liferay-portal/pull/781

**Pull request closed without merging**
